export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
export const GET_RESTAURANTS_FAIL = 'GET_RESTAURANTS_FAIL';

export const GET_RESTAURANT_DETAILS = 'GET_RESTAURANT_DETAILS';
export const GET_RESTAURANT_DETAILS_SUCCESS = 'GET_RESTAURANT_DETAILS_SUCCESS';
export const GET_RESTAURANT_DETAILS_FAIL = 'GET_RESTAURANT_DETAILS_FAIL';

export const GET_FAVORITE_RESTAURANTS = 'GET_FAVORITE_RESTAURANTS';
export const GET_FAVORITE_RESTAURANTS_SUCCESS =
  'GET_FAVORITE_RESTAURANTS_SUCCESS';
export const GET_FAVORITE_RESTAURANTS_FAIL = 'GET_FAVORITE_RESTAURANTS_FAIL';

export const TOGGLE_FAVORITE_RESTAURANT = 'TOGGLE_FAVORITE_RESTAURANT';
export const TOGGLE_FAVORITE_RESTAURANT_SUCCESS =
  'TOGGLE_FAVORITE_RESTAURANT_SUCCESS';
export const TOGGLE_FAVORITE_RESTAURANT_FAIL =
  'TOGGLE_FAVORITE_RESTAURANT_FAIL';
